# CI workflow for validating action
name: Build
on:
  - pull_request
jobs:
  run:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Run PSRule analysis
      uses: ./
      with:
        inputType: repository
        outputFormat: NUnit3
        outputPath: reports/ps-rule-results.xml

    - name: PSRule results
      uses: actions/upload-artifact@v2.1.4
      if: always()
      with:
        name: PSRule-results
        path: reports/ps-rule-results.xml
